# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# SENTIMENTAL ANALYSIS
# =============================================================================

  sentimental-analysis:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - sentimental
    volumes:
      - log:/var/log/sentiment-analysis/

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  sentimental-analysis:

# =============================================================================
# VOLUMES
# =============================================================================

volumes:
  log:
