version: "3.8"

# ==============================================================================
# ANCHORS
# ==============================================================================

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

x-entrypoint: &default-entrypoint
  entrypoint: >
    /bin/sh -c "
      set -e
      chmod a+x /usr/local/bin/wait && \
        /usr/local/bin/wait && echo Hello
      /bin/bash || exit 0
    "

x-volumes: &default-volumes
  volumes:
    - ./scripts/wait:/usr/local/bin/wait

# ==============================================================================
# SERVICES
# ==============================================================================

services:

  sentimental-analysis:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
